#cloud-config
users:
  - name: fox
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ+m7Mzap9kCF+2n6iWXSGdq+cFLZoQEqJiiya17Zvbu yuri@ubuntu-work