apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        env:
         - name: REDIS_PASSWORD
           value: "{{ .Values.redisPassword }}"
        ports:
        - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
  type: {{ .Values.service.type }}