#cloud-config
users:
  - name: fox
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDcWmvMaqLLz21oRwKNRh+v143lcuAocua3h++gUbQnt yuri@ubuntu-home